"""
render_base.py — Email HTML rendering primitives (all English)
"""
from __future__ import annotations
import html
import re
from datetime import datetime, UTC

# ── Design tokens ─────────────────────────────────────────────────────────────
BG      = "#f8f8fa"
SURFACE = "#ffffff"
BORDER  = "#e2e2ea"
MUTED   = "#8a8a9a"
TEXT    = "#1c1c2a"
ACCENT  = "#2563eb"
TAG_BG  = "#f0f0f6"

FONT = ("'Helvetica Neue',Arial,'Liberation Sans',"
        "'PingFang SC','Hiragino Sans GB','Microsoft YaHei',sans-serif")
MONO = "ui-monospace,'Cascadia Code','Menlo','Consolas',monospace"


# ── Date helpers ──────────────────────────────────────────────────────────────

WEEKDAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

def fmt_date(dt: datetime | None = None) -> str:
    if dt is None:
        dt = datetime.now(UTC)
    wd = WEEKDAYS[dt.weekday()]
    return dt.strftime(f"{wd}, %B %-d, %Y")


def fmt_date_range(start: datetime, end: datetime) -> str:
    return f"{start.strftime('%b %-d')} – {end.strftime('%b %-d, %Y')}"


# ── Text helpers ──────────────────────────────────────────────────────────────

def excerpt(text: str, chars: int = 200) -> str:
    if not text:
        return ""
    flat = " ".join(text.split())
    return flat if len(flat) <= chars else flat[:chars].rsplit(" ", 1)[0] + "…"


def md_to_html(text: str) -> str:
    """Minimal markdown → HTML: paragraphs, bold, inline links, bullet lists."""
    if not text:
        return ""
    text = html.escape(text)
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(
        r"\[([^\]]+)\]\((https?://[^\)]+)\)",
        r'<a href="\2" style="color:' + ACCENT + r'">\1</a>',
        text,
    )
    lines = text.split("\n")
    out, in_ul = [], False
    for line in lines:
        if re.match(r"^[-*] ", line):
            if not in_ul:
                out.append("<ul style='margin:8px 0 8px 18px;padding:0'>")
                in_ul = True
            out.append(f"<li style='margin:3px 0;line-height:1.65'>{line[2:]}</li>")
        else:
            if in_ul:
                out.append("</ul>")
                in_ul = False
            if line.strip():
                out.append(f"<p style='margin:0 0 10px;line-height:1.75'>{line}</p>")
    if in_ul:
        out.append("</ul>")
    return "\n".join(out)


# ── Email shell ───────────────────────────────────────────────────────────────

def email_shell(title: str, subtitle: str, body: str, issue_label: str = "") -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="color-scheme" content="light">
</head>
<body style="margin:0;padding:0;background:{BG};font-family:{FONT};color:{TEXT};
             -webkit-text-size-adjust:100%">
<div style="max-width:660px;margin:0 auto;padding:36px 20px 64px">

  <header style="padding-bottom:20px;margin-bottom:32px;border-bottom:2px solid {TEXT}">
    <p style="margin:0 0 6px;font-size:10px;font-weight:700;letter-spacing:.12em;
              text-transform:uppercase;color:{MUTED};font-family:{MONO}"
    >Dewsletter &middot; {html.escape(issue_label)}</p>
    <h1 style="margin:0 0 8px;font-size:26px;font-weight:700;
               letter-spacing:-.02em;line-height:1.2;color:{TEXT}">{html.escape(title)}</h1>
    <p style="margin:0;font-size:13px;color:{MUTED};line-height:1.5">{html.escape(subtitle)}</p>
  </header>

  <main>{body}</main>

  <footer style="margin-top:48px;padding-top:20px;border-top:1px solid {BORDER}">
    <p style="margin:0;font-size:11px;color:{MUTED};line-height:1.6">
      Generated by <strong style="color:{TEXT}">Dewsletter</strong>
      &middot; GitHub Actions &middot; RSS aggregator
    </p>
  </footer>

</div>
</body>
</html>"""


# ── Section heading ───────────────────────────────────────────────────────────

def section_heading(label: str, count: int | None = None) -> str:
    cnt = (f" <span style='font-weight:400;color:{MUTED}'>({count})</span>"
           if count is not None else "")
    return (
        f'<div style="margin:40px 0 16px;padding-bottom:8px;border-bottom:1px solid {BORDER}">'
        f'<p style="margin:0;font-size:10px;font-weight:700;letter-spacing:.12em;'
        f'text-transform:uppercase;color:{MUTED};font-family:{MONO}">'
        f'{html.escape(label)}{cnt}</p></div>'
    )


# ── Block renderers ───────────────────────────────────────────────────────────

def block_full(title: str, source_name: str, url: str,
               content: str, read_minutes: int, sep: bool = True) -> str:
    sep_css = f"border-top:1px solid {BORDER};padding-top:24px;margin-top:24px;" if sep else ""
    rm      = f" &middot; ~{read_minutes} min" if read_minutes else ""
    return f"""
<article style="{sep_css}">
  <p style="margin:0 0 5px;font-size:10px;font-weight:700;letter-spacing:.10em;
            text-transform:uppercase;color:{MUTED};font-family:{MONO}"
  >{html.escape(source_name)}{rm}</p>
  <h2 style="margin:0 0 12px;font-size:19px;font-weight:700;line-height:1.35;
             letter-spacing:-.01em;color:{TEXT}">
    <a href="{html.escape(url)}" style="color:inherit;text-decoration:none"
    >{html.escape(title or '(untitled)')}</a>
  </h2>
  <div style="font-size:14px;line-height:1.75;color:{TEXT}">{md_to_html(content)}</div>
</article>"""


def block_title_excerpt(title: str, source_name: str, url: str,
                        content: str, sep: bool = True) -> str:
    sep_css = f"border-top:1px solid {BORDER};padding-top:20px;margin-top:20px;" if sep else ""
    pre     = html.escape(excerpt(content, 180))
    return f"""
<article style="{sep_css}">
  <p style="margin:0 0 4px;font-size:10px;font-weight:700;letter-spacing:.10em;
            text-transform:uppercase;color:{MUTED};font-family:{MONO}"
  >{html.escape(source_name)}</p>
  <h3 style="margin:0 0 8px;font-size:16px;font-weight:600;line-height:1.4;color:{TEXT}">
    <a href="{html.escape(url)}" style="color:inherit;text-decoration:none"
    >{html.escape(title or '(untitled)')}</a>
  </h3>
  <p style="margin:0 0 8px;font-size:13px;line-height:1.65;color:{TEXT}">{pre}</p>
  <a href="{html.escape(url)}" style="font-size:12px;color:{ACCENT};text-decoration:none"
  >Read more &rarr;</a>
</article>"""


def block_title_only(title: str, source_name: str, url: str) -> str:
    return (
        f'<li style="margin:6px 0;font-size:13px;line-height:1.5">'
        f'<a href="{html.escape(url)}" style="color:{TEXT};text-decoration:none">'
        f'{html.escape(title or "(untitled)")}</a>'
        f' <span style="color:{MUTED};font-size:11px">&mdash; {html.escape(source_name)}</span>'
        f'</li>'
    )


def block_repo_card(title: str, source_name: str, url: str,
                    content: str, sep: bool = True) -> str:
    sep_css = f"border-top:1px solid {BORDER};padding-top:16px;margin-top:16px;" if sep else ""
    desc    = html.escape(excerpt(content, 120))
    return f"""
<article style="{sep_css}">
  <p style="margin:0 0 3px;font-size:10px;font-weight:700;letter-spacing:.10em;
            text-transform:uppercase;color:{MUTED};font-family:{MONO}"
  >{html.escape(source_name)}</p>
  <h3 style="margin:0 0 5px;font-size:15px;font-weight:600;font-family:{MONO};color:{ACCENT}">
    <a href="{html.escape(url)}" style="color:inherit;text-decoration:none"
    >{html.escape(title or '')}</a>
  </h3>
  <p style="margin:0;font-size:13px;line-height:1.55;color:{TEXT}">{desc}</p>
</article>"""


def block_hn(title: str, url: str, score: int,
             by: str, descendants: int, hn_url: str) -> str:
    link = html.escape(url or hn_url)
    hu   = html.escape(hn_url)
    return (
        f'<li style="margin:8px 0;font-size:13px;line-height:1.5">'
        f'<a href="{link}" style="color:{TEXT};text-decoration:none;font-weight:500">'
        f'{html.escape(title or "")}</a>'
        f' <span style="color:{MUTED};font-size:11px;font-family:{MONO}">'
        f'&#9650;{score} &middot; {html.escape(by)} &middot; '
        f'<a href="{hu}" style="color:{MUTED}">{descendants} comments</a>'
        f'</span></li>'
    )


def chart_table(markdown_table: str) -> str:
    """Convert markdown table to HTML table."""
    lines = [l for l in markdown_table.strip().splitlines() if l.strip()]
    if len(lines) < 3:
        return (f"<pre style='font-family:{MONO};font-size:12px'>"
                f"{html.escape(markdown_table)}</pre>")

    def row(cells: list[str], tag: str) -> str:
        return "<tr>" + "".join(
            f"<{tag} style='padding:6px 12px;text-align:left;"
            f"border-bottom:1px solid {BORDER}'>{html.escape(c.strip())}</{tag}>"
            for c in cells if c.strip()
        ) + "</tr>"

    rows = []
    for i, line in enumerate(lines):
        if "|---" in line:
            continue
        cells = line.split("|")[1:-1]  # strip outer pipes
        rows.append(row(cells, "th" if i == 0 else "td"))

    return (f'<table style="width:100%;border-collapse:collapse;font-size:13px;margin:12px 0">'
            f'{"".join(rows)}</table>')
